version: '3'

services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - djangonetwork
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db 
    links:
      - db:db
    networks:
      - djangonetwork   
  angular-nginx-docker:
    image: angular-nginx
    build: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 4200:80
  
volumes:
  data:
  pgdata:

networks:
  djangonetwork:
    driver: bridge
